module.exports = [
    {
        id: 1,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1705839052
    },
    {
        id: 2,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1705857052
    },
    {
        id: 3,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1705857052
    },
    {
        id: 4,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1705921852
    },
    {
        id: 5,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1705943452
    },
    {
        id: 6,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1705965052
    },
    {
        id: 7,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706008252
    },
    {
        id: 8,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706026252
    },
    {
        id: 9,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706051452
    },
    {
        id: 10,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706094652
    },
    {
        id: 11,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706116252
    },
    {
        id: 12,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706137852
    },
    {
        id: 13,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706202652
    },
    {
        id: 14,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706224252
    },
    {
        id: 15,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706267452
    },
    {
        id: 16,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706289052
    },
    {
        id: 17,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706310652
    },
    {
        id: 18,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706353852
    },
    {
        id: 19,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706375452
    },
    {
        id: 20,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706397052
    },
    {
        id: 21,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706440252
    },
    {
        id: 22,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706461852
    },
    {
        id: 23,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706483452
    },
    {
        id: 24,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706526652
    },
    {
        id: 25,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706548252
    },
    {
        id: 26,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706569852
    },
    {
        id: 27,
        name: "Bryce Borer",
        email: "bryce@brainstation.com",
        age: 36,
        sex: "male",
        height: 176,
        weight: 75,
        goal_weight: 50,
        exercise_level: 350,
        activity_level: 250,
        tdee: 2074,
        ideal_carbs: 225,
        ideal_protein: 225,
        ideal_fat: 225,
        ideal_sugar: 225,
        ideal_carbs: 225,
        food_name: "cheerios",
        portion: 200,
        calories: 756,
        carbs: 164.7,
        protein: 15,
        sugar: 16,
        created_at: 1706613052
    },


];